**Partie 1 — Series**
1. Qu'est-ce qu'une Series ?

Une Series Pandas est une structure de données unidimensionnelle avec un index.

Tu peux la voir comme :

index     valeur

  0        24.5

  1        25.1


Elle possède donc principalement :

des valeurs
un index

Pandas permet de créer une Series avec :

pd.Series(...)

Avant de commencer, importe Pandas :

import pandas as pd

In [23]:
import pandas as pd

temperatures = pd.Series([24.5, 25.1, 26.3, 27.0])

temperatures

0    24.5
1    25.1
2    26.3
3    27.0
dtype: float64

**Concept :** pd.Series() crée une structure de données unidimensionnelle composée de valeurs associées à un index.

Par défaut, Pandas crée automatiquement l'index :

0, 1, 2, 3
### 2. Afficher son index

In [24]:
temperatures.index

RangeIndex(start=0, stop=4, step=1)

.index permet d'accéder à l'index de la Series.

Ici :

start=0 → l'index commence à 0 ;
stop=4 → s'arrête avant 4 ;
step=1 → avance de 1.
### 3. Afficher la 1ère valeur

In [25]:
temperatures.iloc[0]

np.float64(24.5)

.iloc[] sélectionne une valeur selon sa position.

iloc[0] → première position

iloc[1] → deuxième position

### 4. Afficher la dernière valeur

In [26]:
temperatures.iloc[-1]

np.float64(27.0)

### 5. Créer, de deux façons différentes, une Series de 4 températures avec les heures comme index

**Les heures demandées sont :**

12h, 13h, 14h, 15h

**Méthode 1 — avec index=**

In [27]:
temperatures_heures = pd.Series(
    [24.5, 25.1, 26.3, 27.0],
    index=["12h", "13h", "14h", "15h"]
)

temperatures_heures

12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

Ici, on fournit séparément :

values = [24.5, 25.1, 26.3, 27.0]
index = ["12h", "13h", "14h", "15h"]

**Méthode 2 — avec un dictionnaire**

In [28]:
temperatures_heures = pd.Series({
    "12h": 24.5,
    "13h": 25.1,
    "14h": 26.3,
    "15h": 27.0
})

temperatures_heures

12h    24.5
13h    25.1
14h    26.3
15h    27.0
dtype: float64

Ici, Pandas utilise directement :

clé        → index

valeur     → donnée

### 6. Afficher la 1ère et la dernière valeur

In [29]:
premiere = temperatures_heures.iloc[0]
derniere = temperatures_heures.iloc[-1]

premiere, derniere

(np.float64(24.5), np.float64(27.0))

**Pourquoi iloc ici ?**

Même si notre index contient maintenant "12h", "13h", etc., la question demande la première et la dernière valeur, donc on travaille avec leur position :

temperatures_heures.iloc[0]   # première
temperatures_heures.iloc[-1]  # dernière

À l'inverse, si on voulait précisément la température de 12h, on pourrait utiliser le label :

temperatures_heures["12h"]

On approfondira cette différence avec loc / iloc à la question 4 de l'atelier.

# Partie 2 – DataFrame

Un DataFrame est une structure de données bidimensionnelle, organisée en lignes et colonnes.
On peut le comparer à un tableau Excel :
un dataframe se comporte comme un dictionnaire dont les clefs sont les noms des colonnes et les valeurs sont des séries.
on peut le créer à partir d'une array numpy (mais ce n'est pas très pratique et le type des données est le même pour toutes les colonnes, ici float64)
1) Créer et afficher le dataframe df_test à partir du dictionnaire suivant

In [30]:

data = {
"capteur": ["C001", "C002", "C003"],
"temperature": [24.5, 25.1, 26.3],
"humidite": [65, 67, 70]
}
df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70


**2) Importer le dataset mesures_capteurs.csv dans le dataframe df**

In [35]:
df = pd.read_csv("../data/mesures_capteurs.csv")

df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

**3) Afficher les dimensions de df**

In [36]:
df.shape

(605, 9)

# Partie 3 – Exploration

**1) Afficher les premières lignes**

In [37]:
df.head()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

**2) Afficher les 10 premières lignes**

In [38]:
df.head(10)

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
5,M0595,2026-01-29 18:00:00,C007,B003,24.51,58.01,1013.34,146.10,OK
6,M0011,2026-01-05 10:00:00,C011,B004,29.23,70.43,1007.68,290.45,OK
7,M0132,2026-01-10 11:00:00,C012,B004,31.21,60.57,1024.64,285.92,OK
8,M0444,2026-01-23 11:00:00,C012,B004,23.11,82.06,1021.96,293.36,OK
9,M0087,2026-01-08 14:00:00,C003,B001,28.85,44.37,1008.27,206.59,OK

3) Afficher les dernières lignes

In [39]:
df.tail()

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK


**4) Afficher le nombre de lignes**

In [41]:
df.shape[0]

605

5) Afficher le nombre de colonnes

In [42]:
df.shape[1]

9

6) Afficher les noms des colonnes

In [43]:
df.columns

Index(['id_mesure', 'date_heure', 'id_capteur', 'batiment', 'temperature',
       'humidite', 'pression', 'consommation', 'etat'],
      dtype='str')

7) Afficher les informations générales

In [44]:
df.columns.tolist()

['id_mesure',
 'date_heure',
 'id_capteur',
 'batiment',
 'temperature',
 'humidite',
 'pression',
 'consommation',
 'etat']

**7) Afficher les informations générales**

In [45]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_mesure     605 non-null    str
 1   date_heure    605 non-null    str
 2   id_capteur    605 non-null    str
 3   batiment      605 non-null    str
 4   temperature   599 non-null    float64
 5   humidite      600 non-null    float64
 6   pression      600 non-null    float64
 7   consommation  600 non-null    float64
 8   etat          601 non-null    str
dtypes: float64(4), str(5)
memory usage: 42.7 KB

**8) Afficher les statistiques descriptives**

In [46]:
df.describe()

       temperature   humidite     pression  consommation
count   599.000000  600.00000   600.000000    600.000000
mean     24.878314   64.92620  1012.221900    208.675417
std       4.059576   10.76905    10.599042     72.243567
min     -18.500000   28.52000   850.000000     18.120000
25%      22.570000   58.17250  1006.790000    160.177500
50%      24.860000   65.37500  1012.855000    206.150000
75%      27.275000   71.61500  1017.827500    254.127500
max      58.700000  145.00000  1038.430000    875.000000

# Partie 4 – Sélection

**1) Sélectionner la colonne "temperature"**

In [47]:
df["temperature"]

0      25.46
1      24.00
2      25.82
3      28.23
4      20.58
       ...
600    23.67
601    24.34
602    23.73
603    24.83
604    17.02
Name: temperature, Length: 605, dtype: float64

**2) Sélectionner les colonnes "temperature", "humidite", "pression" et "consommation"**

In [52]:
df[['temperature','humidite','pression','consommation']]

     temperature  humidite  pression  consommation
0          25.46     58.06   1008.95        287.28
1          24.00     79.73    993.39        116.20
2          25.82     54.47   1010.32        288.50
3          28.23     69.39   1019.62        136.65
4          20.58     53.80   1016.58        182.62
..           ...       ...       ...           ...
600        23.67     60.28   1015.11        282.36
601        24.34     61.42   1019.43        357.43
602        23.73     63.49   1016.46        152.79
603        24.83     79.77   1017.05        170.97
604        17.02     52.04   1001.14         44.99

[605 rows x 4 columns]

****3) Sélectionner les 5 premières lignes avec loc
****

loc permet de sélectionner des données en utilisant les labels de l'index et des colonnes.

In [55]:
df.loc[0:4]

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK

**4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc
**

iloc sélectionne selon la position numérique.

**4) Sélectionner les 5 premières lignes et les 4 premières colonnes avec iloc**

In [57]:
df.iloc[0:5, 0:4]

  id_mesure           date_heure id_capteur batiment
0     M0413  2026-01-22 04:00:00       C005     B002
1     M0290  2026-01-17 01:00:00       C002     B001
2     M0077  2026-01-08 04:00:00       C005     B002
3     M0079  2026-01-08 06:00:00       C007     B003
4     M0183  2026-01-12 14:00:00       C003     B001